### PR TITLE
Reworked query.promote_joins() call to work with Django 1.5-1.6 and 1.7 ...

### PR DESCRIPTION
**Pull request by end0**
...(which drops the unconditional arg)

### CODE REVIEW

**Comment by end0** [comment]
In response to my own issue #8

**Comment by henriquebastos** [comment]
Nice! I'll merge it and check if the 1st issue still applies. After that I'll release 0.5 with you contribution. Tks a lot.

**Comment by end0** [comment]
p.s. - I noticed Travis CI is running up to Django 1.6. May be useful to load 1.7rc2 on there just to make sure all tests still pass. I wasn't able to run your testsuite locally.

**Comment by owais** [comment]
@henriquebastos @end0 Thanks guys! Waiting on 0.5 release.

**Comment by kawa-marcin** [comment]
Hello, can I ask for merge it?
Cheers

**Comment by end0** [comment]
@henriquebastos Sorry to bother again, but can you complete the PR? Now that 1.7 is out, I'm working on a real project, and would prefer to use your version over my fork.

**Comment by henriquebastos** [comment]
I'm unifying this discussion on a new PR: https://github.com/henriquebastos/django-aggregate-if/pull/11

**Pull request closed without merging**
